In [1]:
import torch

In [2]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
y = torch.tensor([[7, 8, 9], [10, 11, 12]])
z = x + y # follows same principles as matrices, except broadcasting?
print(z)

tensor([[ 8, 10, 12],
        [14, 16, 18]])


In [3]:
print(z.size())

torch.Size([2, 3])


In [8]:
print(z.shape)

torch.Size([2, 3])


In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
x = torch.tensor([[1, 2, 3], [4, 5, 6]], device=device)
y = torch.tensor([[7, 8, 9], [10, 11, 12]], device=device)
z = x + y
print(z)

tensor([[ 8, 10, 12],
        [14, 16, 18]], device='cuda:0')


In [10]:
print(z.device)

cuda:0


In [11]:
# moving tensors b/w cpu and gpu
x.to(device)
y.to(device)
z = x + y
z.to("cpu")

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [12]:
# creating tensors
import numpy as np

# from existing arrays
w = torch.tensor([1, 2, 3])
w = torch.tensor([1, 2, 3])
w = torch.tensor(np.array([1, 2, 3]))

In [13]:
# init by size
w = torch.empty(100, 200)
w = torch.zeros(100, 200)
w = torch.ones(100, 200)

In [16]:
# init by size with random vals
w = torch.rand(100, 200)
w = torch.randn(100, 200)
w = torch.randint(5, 10, (100, 200))
w.shape

torch.Size([100, 200])

In [18]:
w = torch.empty((100, 200), dtype=torch.float64, device="cuda") # specified data type and device
w

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)

In [20]:
x = torch.empty_like(w) # same size, data type, device as w
x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.float64)

In [21]:
# data types
w = torch.tensor([1, 2, 3], dtype=torch.float32)

w.int() # w remains float32
w = w.int() # w changes to int32

# use to() to cast
w = w.to(torch.float64)
w = w.to(dtype=torch.float64)

# auto conversion by python
x = torch.tensor([1, 2, 3], dtype=torch.int32)
y = torch.tensor([1, 2, 3], dtype=torch.float32)
z = x + y # z is float32
print(z.dtype)

torch.float32


In [26]:
x = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
print(x)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [27]:
# indexing, returns tensor
print(x[0, 1])

# incexing return scalar
print(x[0, 1].item())

tensor(2)
2


In [28]:
# sliceing
print(x[:2,1])

print(x[x<5])

tensor([2, 4])
tensor([1, 2, 3, 4])


In [29]:
print(x.t()) # transpose

print(x.view((2, 4))) # changing shape, view() over reshape()

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [30]:
y = torch.stack((x, x)) # combining tensors
print(y)

# splitting
a, b = x.unbind(dim=1)
print(a, b)

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])
tensor([1, 3, 5, 7]) tensor([2, 4, 6, 8])


In [31]:
## automatic differentiation (autograd)
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float, requires_grad=True)
print(x)

f = x.pow(2).sum()
print(f)

f.backward()
print(x.grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
tensor(91., grad_fn=<SumBackward0>)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
